### ISSUE TITLE
Add design editor support.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-boulder#62]
- [x] Setup grunt task to build `.tpl` component from sources stylesheet.
- [x] Add custom styles component to `template-head.tpl`.
- [x] Add editor functionality.

**Comment by SSirjes** [comment]
_I round testing (19.05.16)_

**Comment by kaspar-naaber** [comment]
- [ ] Add content width editor.

**Comment by kaspar-naaber** [comment]
- [ ] Cleanup code.

**Comment by SSirjes** [comment]
_II round testing (23.05.16)_

* [ ] **Header-Main menu hover styles(italic, uppercase) applying also to active menu item**
_Video: http://recordit.co/BA3eHQ8pyy_

**Comment by SSirjes** [comment]
* [ ] **Front page Blog options don't work**
_Video: http://recordit.co/hcQtm5WtWN_

* [ ] **Internet Explorer don't get Content background color**
